# Generated by Django 5.2.14 on 2026-05-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('role_applied_for', models.CharField(max_length=100)),
                ('application_source', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=100)),
                ('interview_round', models.CharField(max_length=100)),
                ('communication_skills', models.CharField(max_length=50)),
                ('technical_skills', models.CharField(max_length=50)),
                ('sales_orientation', models.CharField(max_length=50)),
                ('recruiter_name', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=255)),
                ('next_action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
